language: generic
cache:
  directories:
  - $HOME/texlive
matrix:
  include:
  - os: linux
    sudo: false
    addons:
      apt:
        packages:
        - texlive-luatex
    env: TEX=apt
  - os: linux
    sudo: false
    env: TEX=texlive
  - os: osx
    env: TEX=texlive
install:
- if [[ "$TEX" == "texlive" ]]; then eval $(sh ci/texlive.sh); fi
before_script:
- luatex --version
