cache:
  - '%USERPROFILE%\texlive'
install:
  - ps: .\ci\texlive.ps1
before_build:
  - luatex --version
  - git submodule init
  - git submodule update
build_script:
  - texlua build.lua
test_script:
  - runscript tlperl test_texlua.pl
  - runscript tlperl test_luatex.pl
  - runscript tlperl test_texlua.pl texluajit --jiton
  - runscript tlperl test_luatex.pl luajittex --jiton
